version: '2.5'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    networks:
      - inception
    restart: always
 
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - /home/llecoq/data/DB:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - inception
    stdin_open: true
    tty: true
    volumes:
      - /home/llecoq/data/wordpress:/usr/share/webapps/wordpress/
    restart: always

networks:
  inception:

# volumes:
#   db-data: 