version: '2.5'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    restart: always
 
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - /home/llecoq/data/DB:/var/lib/mysql
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - 9000:9000
    stdin_open: true
    tty: true
    volumes:
      - /home/llecoq/data/wordpress:/usr/share/webapps/wordpress/
    restart: always

# volumes:
#   db-data: 