version: '2.5'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - 443:443
    networks:
      - intra
    volumes:
      - WordPress:${NGINX_PATH}
    depends_on:
      - wordpress
    restart: always
 
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - 3306:3306
    networks:
      - intra
    volumes:
      - DB:/var/lib/mysql
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - 9000:9000
    networks:
      - intra
    volumes:
      - WordPress:${WORDPRESS_PATH}
    depends_on:
      - mariadb
    restart: always

networks:
  intra:
    driver: bridge
    name: ${PROJECT_NAME}

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/DB/
  WordPress:
    name: WordPress
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /home/${LOGIN}/data/WordPress/