version: '2.5'

services:
  nginx:
    build: requirements/nginx
    ports:
      - 443:443
    restart: always
 
  # mariadb:
  #   build: requirements/mariadb
  #   ports:
  #     - 3306:3306
  #   stdin_open: true
  #   tty: true
  #   # restart: always